source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'zzjDown' do
    pod 'Alamofire'
    pod 'Kingfisher','~>2.6'
    pod 'SnapKit','~>0.22.0'
    pod 'MJRefresh'
    pod 'SwiftyXMLParser'
end
